name: Deploy PR to Pantheon

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    permissions:
      deployments: write
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: First sentence
      shell: bash
      env:
        YOUR_NAME: "Steve Persch"
      run: |
        echo "Hi, I'm ${YOUR_NAME} from Pantheon."
        echo "and I want to tell you about our new Github Action."
        sleep 10;

    - name: second sentence
      shell: bash
      # env:
      #   YOUR_NAME: "Steve Persch"
      run: |
        echo "Writing CI scripts can be time consiming."
        echo "You need to install Terminus,"
        echo "you need to set up SSH keys and access tokens."
        sleep 10;

    - name: deploy to Pantheon
      uses: ./
      with:
        ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
        machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
        site: dtp-nearly-empty-site
        target_env: "pr-${{ github.event.pull_request.number }}"
        relative_site_root: ".github/testing_fixtures/dtp-nearly-empty-site"
        git_user_name: "Test Name"
        git_user_email: "test@example.com"
        git_commit_message: "This is an automated commit message from GitHub Actions."
        delete_old_environments: true
        clone_content: true
