name: Manual Deploy Branch to Pantheon

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  workflow_dispatch:

jobs:
  test_workflow:
    name: Test Workflow Manually
    permissions:
      deployments: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@v1.2.7
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    - name: Run Terminus Command
      run: |
        terminus --version
        terminus art
        terminus auth:whoami
        terminus site:info dtp-nearly-empty-site
      shell: bash
    - name: Set short branch name
      id: vars
      run: echo "short_ref_name=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9-]//g' | cut -c1-6)" >> $GITHUB_OUTPUT
    - name: deploy to Pantheon
      uses: ./
      with:
        ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
        machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
        site: dtp-nearly-empty-site
        target_env: "test-${{ steps.vars.outputs.short_ref_name }}"
        relative_site_root: ".github/testing_fixtures/dtp-nearly-empty-site"
        git_user_name: "Test Name"
        git_user_email: "test@example.com"
        git_commit_message: "This is a manual test deployment from GitHub Actions."
        clone_content: true