name: Shellcheck
on:
  push:
    paths:
      - 'scripts/**'
      - 'tests/helpers/*.bash'
      - '.github/workflows/shellcheck.yml'

permissions:
  contents: read

jobs:
  shellcheck:
    name: Run Shellcheck on Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Run Shellcheck
        run: |
          shellcheck scripts/*.sh
          shellcheck tests/helpers/*.bash